GET http://127.0.0.1:3000/cars
###
PATCH http://127.0.0.1:3000/cars/2?status=reserved
###
DELETE http://127.0.0.1:3000/cars/3
###
POST http://127.0.0.1:3000/cars
Content-Type: application/json

{
    "title": "Bargain!",
    "status": "available",
    "price": "367.100 $",
    "image": "http://localhost:3000/images/car9.png",
    "miles": 85549,
    "yearOfMake": 2012,
    "owner": {
        "firstName": "Robert",
        "lastName": "Baumgartner"
        },
    "description": "Lorem ipsum dolor sit amet." 
}
